# Uses https://github.com/pascalgn/automerge-action and https://github.com/actions/labeler

name: Auto-merge
on: 
  pull_request:
    types: [ opened, synchronize, reopened ]
  check_suite:
    types: [ completed ]

permissions: write-all
  
  
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps: 
      - name: Auto-label
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automerge,!work in progress,!ready for review"
          MERGE_REMOVE_LABELS: "automerge"
          LOG: DEBUG
