# Uses https://github.com/pascalgn/automerge-action and https://github.com/actions/labeler

name: Auto-merge
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  check_suite:
    types: [ completed ]

permissions:
  contents: read
  pull-requests: write


jobs:
  autolabel:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label
        uses: actions/labeler@8558fd74291d67161a8a78ce36a648edfd2f1054 # actions/labeler@v5
        with:
          repo-token: ${{ secrets.AUTOMERGE_PAT }}
  automerge:
    needs: autolabel
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge
        uses: pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584 # pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_PAT }}
          MERGE_LABELS: "automerge,!work in progress,!ready for review"
          MERGE_REMOVE_LABELS: "automerge"
          LOG: DEBUG
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 60000
