# Uses https://github.com/pascalgn/automerge-action and https://github.com/actions/labeler

name: Auto-merge
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  check_suite:
    types: [ completed ]

permissions: write-all


jobs:
  autolabel:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # actions/labeler@v4
        with:
          repo-token: ${{ secrets.AUTOMERGE_PAT }}
  automerge:
    needs: autolabel
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge
        uses: pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584 # pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_PAT }}
          MERGE_LABELS: "automerge,!work in progress,!ready for review"
          MERGE_REMOVE_LABELS: "automerge"
          LOG: DEBUG
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 60000
