name: Rebase Pull Requests
on:
  push:
    branches: '**'
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: linhbn123/rebase-pull-requests@597051eba1a01661fe4b2580d618eeaa9c524d1b # linhbn123/rebase-pull-requests@v1.0.1
